# Site settings
title: iOS Development Guide
description: A comprehensive roadmap for iOS development

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  tutorials:
    output: true
